// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function parseData(p) {
  return p[/* age */0];
}

function validateAge(age) {
  var match = age > 122;
  if (match) {
    return "you can't";
  } else {
    return "sorry";
  }
}

var res = "sorry";

var person = /* record */[
  /* age */10,
  /* name */"allan"
];

exports.person = person;
exports.parseData = parseData;
exports.validateAge = validateAge;
exports.res = res;
/* No side effect */
