// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var kraken = /* record */[
  /* age */9999,
  /* hasTentacles */true
];

var t = /* tuple */[
  10,
  10,
  "string"
];

var test = /* Yes */0;

exports.kraken = kraken;
exports.t = t;
exports.test = test;
/* No side effect */
