// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Http = require("bs-node-http/src/Http.js");
var Http$1 = require("http");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var server = Http$1.createServer((function (request, response) {
        var match = Http.ClientRequest[/* getMethod */0](request);
        if (match !== 3546230) {
          if (match !== 3997359) {
            if (match !== 891112544) {
              Pervasives.print_string("We don't accept other methods...");
            } else {
              Pervasives.print_string("POSTman Pat");
            }
          } else {
            Pervasives.print_string("PUTting the tee-pee in HTTP");
          }
        } else {
          Pervasives.print_string("GET money, GET paid");
        }
        var partial_arg = Http.ServerResponse[/* write */4];
        Http.ServerResponse[/* write */4]("UmVhc29uTUwgaXMgcHJldHR5IGdyZWF0IQ==", /* base64 */-718799473, (function (eta) {
                    var param = undefined;
                    var param$1 = eta;
                    return partial_arg("Hello, world! I am a teapot!", param, param$1);
                  })(Http.ServerResponse[/* setHeader */1]("x-reason", "reason-ml", Http.ServerResponse[/* setStatusCode */2](418, response)))).end();
        return /* () */0;
      }));

server.listen(3000);

exports.server = server;
/* server Not a pure module */
